# glycoMusubi Shiny App — Global Data Loading
# Loaded once at app startup; shared across all sessions.

library(shiny)
library(bslib)
library(DT)
library(plotly)
library(visNetwork)
library(dplyr)
library(readr)
library(jsonlite)
library(arrow)
library(tidyr)
library(stringr)

# ── Source utilities ──
source("R/utils.R")

# ── Paths (env vars for Docker, fallback for local) ──
BASE <- normalizePath(file.path(".."), mustWork = FALSE)
KG_DIR <- Sys.getenv("GLYCOKG_KG_DIR", file.path(BASE, "kg"))
DATA_DIR <- Sys.getenv("GLYCOKG_DATA_DIR", file.path(BASE, "data_clean"))
EXP_DIR <- Sys.getenv("GLYCOKG_EXP_DIR", file.path(BASE, "experiments_v2"))
SHINY_DATA <- file.path("data")

# ══════════════════════════════════════════════════════════════
# 1. Knowledge Graph core tables
# ══════════════════════════════════════════════════════════════
message("Loading KG node/edge tables...")

if (file.exists(file.path(KG_DIR, "nodes.parquet"))) {
  kg_nodes <- arrow::read_parquet(file.path(KG_DIR, "nodes.parquet"))
} else {
  kg_nodes <- safe_read_tsv(file.path(KG_DIR, "nodes.tsv"))
}

if (file.exists(file.path(KG_DIR, "edges.parquet"))) {
  kg_edges <- arrow::read_parquet(file.path(KG_DIR, "edges.parquet"))
} else {
  kg_edges <- safe_read_tsv(file.path(KG_DIR, "edges.tsv"))
}

# Node type summary
node_type_summary <- kg_nodes %>%
  count(node_type, name = "count") %>%
  arrange(desc(count))

# Edge relation summary
edge_relation_summary <- kg_edges %>%
  count(relation, name = "count") %>%
  arrange(desc(count))

# ══════════════════════════════════════════════════════════════
# 2. Entity detail tables
# ══════════════════════════════════════════════════════════════
message("Loading entity detail tables...")

proteins_df <- safe_read_tsv(file.path(DATA_DIR, "proteins_clean.tsv"))
glycans_df  <- safe_read_tsv(file.path(DATA_DIR, "glycans_clean.tsv"))

# ══════════════════════════════════════════════════════════════
# 3. Cell-type enzyme expression
# ══════════════════════════════════════════════════════════════
message("Loading cell-type expression data...")

celltype_expr <- safe_read_tsv(
  file.path(DATA_DIR, "ts_celltype_enzyme_expression.tsv")
)

# ══════════════════════════════════════════════════════════════
# 4. Benchmark metrics (all experiments)
# ══════════════════════════════════════════════════════════════
message("Loading benchmark metrics...")

load_experiment_metrics <- function(exp_dir) {
  exp_dirs <- list.dirs(exp_dir, recursive = FALSE, full.names = TRUE)
  metrics_list <- list()
  for (d in exp_dirs) {
    name <- basename(d)
    mfile <- file.path(d, "metrics.json")
    rfile <- file.path(d, "results.json")
    if (file.exists(mfile)) {
      m <- safe_read_json(mfile)
      m$experiment <- name
      metrics_list[[name]] <- m
    } else if (file.exists(rfile)) {
      m <- safe_read_json(rfile)
      m$experiment <- name
      metrics_list[[name]] <- m
    }
  }
  metrics_list
}

all_metrics <- load_experiment_metrics(EXP_DIR)

# ══════════════════════════════════════════════════════════════
# 5. Pre-computed data for Shiny (UMAP, hierarchies, etc.)
# ══════════════════════════════════════════════════════════════
message("Loading pre-computed Shiny data...")

# UMAP coordinates (generated by prepare_shiny_data.py)
umap_glycan_path <- file.path(SHINY_DATA, "umap_glycan_embeddings.tsv")
umap_protein_path <- file.path(SHINY_DATA, "umap_protein_embeddings.tsv")

umap_glycans <- if (file.exists(umap_glycan_path)) {
  safe_read_tsv(umap_glycan_path)
} else {
  data.frame()
}

umap_proteins <- if (file.exists(umap_protein_path)) {
  safe_read_tsv(umap_protein_path)
} else {
  data.frame()
}

# Glycan hierarchy tree
hierarchy_path <- file.path(SHINY_DATA, "glycan_hierarchy.tsv")
glycan_hierarchy <- if (file.exists(hierarchy_path)) {
  safe_read_tsv(hierarchy_path)
} else {
  # Build from edges
  kg_edges %>%
    filter(relation %in% c("parent_of", "child_of")) %>%
    select(source_id, target_id, relation)
}

# Retrieval rankings (pre-computed)
retrieval_path <- file.path(SHINY_DATA, "retrieval_rankings.tsv")
retrieval_rankings <- if (file.exists(retrieval_path)) {
  safe_read_tsv(retrieval_path)
} else {
  data.frame()
}

# Prediction results (pre-computed)
predictions_path <- file.path(SHINY_DATA, "site_predictions.tsv")
site_predictions <- if (file.exists(predictions_path)) {
  safe_read_tsv(predictions_path)
} else {
  data.frame()
}

# ══════════════════════════════════════════════════════════════
# 6. Key statistics for overview
# ══════════════════════════════════════════════════════════════
kg_stats <- list(
  n_nodes = nrow(kg_nodes),
  n_edges = nrow(kg_edges),
  n_node_types = n_distinct(kg_nodes$node_type),
  n_relation_types = n_distinct(kg_edges$relation),
  n_glycans = sum(kg_nodes$node_type == "glycan"),
  n_proteins = sum(kg_nodes$node_type == "protein"),
  n_enzymes = sum(kg_nodes$node_type == "enzyme"),
  n_experiments = length(all_metrics)
)

message("Global data loading complete.")
